- name: Install AWS CLI Dependencies
  apt:
    name: 'unzip'
    state: present
    update_cache: true
  become: true

- name: Checking if AWS CLI is already installed
  stat:
    path: '{{ aws_cli_home_parent_directory }}/aws'
  register: aws_cli_installed
  become: yes

- name: Download AWS CLI zip file
  get_url:
    url: '{{ aws_cli_download_url }}'
    dest: '{{ aws_cli_home_parent_directory }}/{{ aws_cli_file_name }}'
    use_proxy: no
  when: not aws_cli_installed.stat.exists
  become: yes

- name: Unpack AWS CLI zip file
  unarchive:
    src: '{{ aws_cli_home_parent_directory }}/{{ aws_cli_file_name }}'
    dest: '{{ aws_cli_home_parent_directory }}'
    copy: no
  when: not aws_cli_installed.stat.exists
  become: true

- name: Install AWS CLI
  shell: aws/install
  args:
    chdir: '{{ aws_cli_home_parent_directory }}'
  become: true
