- name: Install prerequisites for Docker
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
    update_cache: yes
  become: true

# We copy Docker's conf over before installing Docker in order to ensure Docker picks up the correct data-dir
# setting before we start pulling any images (such as Distbox2) which would otherwise be saved to /var/lib/docker
# when we always want it saved somewhere else (commonly /data/docker)
- name: Ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0700
  become: true

- name: Deploy daemon.json to /etc/docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: true

- name: Add Docker official signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Verify Docker key with fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Add Docker Apt repository  # TODO get distro
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes
  become: true
