- name: Configure WSL
  roles:
    - docker-install
    - helm-install
    - kubectl-install
    - go-install
    - dev-tools-install
    - role: gantsign.oh-my-zsh
      users:
       - username: root
         oh_my_zsh:
          theme: miloshadzic
          plugins:
            - git
            - keychain
            - vscode
