- name: Configure WSL
  hosts: all
  roles:
    - docker-install
    - go-install
    - dev-tools-install
    - git-configure
    - aws-cli-install
    - role: gantsign.oh-my-zsh
      users:
       - username: root
         oh_my_zsh:
          theme: miloshadzic
          plugins:
            - git
            - keychain
            - vscode
